# Generated by Django 5.2 on 2025-05-04 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=10)),
                ('suffix', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resume_link', models.URLField()),
                ('image', models.ImageField(upload_to='media/hero/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('icon_class', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_link', to='base.herosection')),
            ],
        ),
    ]
