# Generated by Django 5.2 on 2025-06-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_funfact_options_alter_herosection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='شماره')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان خدمت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('delay', models.CharField(default='.5s', max_length=10, verbose_name='تاخیر در نمایش انیمیشن')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'لیست خدمات',
            },
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.ImageField(upload_to='hero/', verbose_name='تصویر'),
        ),
    ]
