# Generated by Django 5.2 on 2025-06-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_service_alter_herosection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان خدمت')),
                ('short_description', models.TextField(verbose_name='توضیح کوتاه')),
                ('full_description', models.TextField(verbose_name='توضیحات کامل')),
                ('process', models.TextField(verbose_name='فرایند خدمت')),
                ('image', models.ImageField(upload_to='services/', verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'خدمت(پاپ آپ)',
                'verbose_name_plural': 'لیست خدمات(پاپ آپ)',
            },
        ),
    ]
