# Generated by Django 5.2 on 2025-06-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_popupservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان پورتفولیو')),
                ('description', models.TextField(verbose_name='توضیحات بیشتر')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('category', models.CharField(choices=[('uxui', 'UX/UI'), ('branding', 'BRANDING'), ('web-app', 'WEB APP'), ('mobile-app', 'MOBILE APP')], max_length=20, verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پروژه های اخیر',
                'verbose_name_plural': 'لیست پروژه های اخیر',
            },
        ),
    ]
