# Generated by Django 5.2 on 2025-06-29 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('full_description', models.TextField(verbose_name='توضیحات کامل')),
                ('summary', models.TextField()),
                ('our_approach', models.TextField()),
                ('client', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('uxui', 'UX/UI'), ('branding', 'BRANDING'), ('web-app', 'WEB APP'), ('mobile-app', 'MOBILE APP')], max_length=50, verbose_name='دسته بندی')),
                ('start_date', models.CharField(max_length=100)),
                ('designer', models.CharField(max_length=100)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(upload_to='portfolio/thumbnail/')),
                ('modal_image', models.ImageField(upload_to='portfolio/modal/')),
            ],
            options={
                'verbose_name': 'پروژه های اخیر(بخش پاپ آپ)',
                'verbose_name_plural': 'لیست پروژه های اخیر(بخش پاپ آپ)',
            },
        ),
        migrations.CreateModel(
            name='PortfolioGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='base.portfoliopopup')),
            ],
        ),
    ]
