# Generated by Django 5.2 on 2025-07-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_portfoliopopup_portfoliogallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, verbose_name='نام دوره')),
                ('institute', models.CharField(max_length=100, verbose_name='نام موسسه')),
                ('period', models.CharField(max_length=100, verbose_name='مدت زمان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'تحصیلات',
                'verbose_name_plural': 'سوابق تحصیلی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان شغلی')),
                ('company', models.CharField(max_length=100, verbose_name='محل/شرکت')),
                ('period', models.CharField(max_length=100, verbose_name='مدت زمان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'سابقه کاری',
                'verbose_name_plural': 'سوابق کاری',
                'ordering': ['order'],
            },
        ),
    ]
