# Generated by Django 5.2 on 2025-07-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_education_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان مهارت')),
                ('percentage', models.PositiveIntegerField(verbose_name='درصد مهارت')),
                ('icon', models.ImageField(upload_to='skills/icons/', verbose_name='آیکون مهارت')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
                'ordering': ['order'],
            },
        ),
    ]
